# Generated by Django 5.1.4 on 2026-03-19 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('steps', models.IntegerField(default=0, verbose_name='Steps')),
                ('calories_consumed', models.IntegerField(default=0, verbose_name='Calories (consumed)')),
                ('calories_burned', models.IntegerField(default=0, verbose_name='Calories (burned)')),
                ('water_ml', models.IntegerField(default=0, verbose_name='Water (ml)')),
                ('sleep_hours', models.FloatField(default=0, verbose_name='Sleep (hours)')),
                ('heart_rate_avg', models.IntegerField(default=0, verbose_name='Avg heart rate')),
                ('workout_minutes', models.IntegerField(default=0, verbose_name='Workout (min)')),
                ('recovery_score', models.IntegerField(default=0, verbose_name='Recovery (%)')),
                ('strain_level', models.FloatField(default=0, verbose_name='Strain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health metric',
                'verbose_name_plural': 'Health metrics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
