# Generated by Django 5.1.4 on 2026-03-19 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('steps', models.IntegerField(default=0, verbose_name='Шаги')),
                ('calories_consumed', models.IntegerField(default=0, verbose_name='Калории (потреблено)')),
                ('calories_burned', models.IntegerField(default=0, verbose_name='Калории (сожжено)')),
                ('water_ml', models.IntegerField(default=0, verbose_name='Вода (мл)')),
                ('sleep_hours', models.FloatField(default=0, verbose_name='Сон (часы)')),
                ('heart_rate_avg', models.IntegerField(default=0, verbose_name='Средний пульс')),
                ('workout_minutes', models.IntegerField(default=0, verbose_name='Тренировка (мин)')),
                ('recovery_score', models.IntegerField(default=0, verbose_name='Восстановление (%)')),
                ('strain_level', models.FloatField(default=0, verbose_name='Нагрузка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Метрика здоровья',
                'verbose_name_plural': 'Метрики здоровья',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
